### ISSUE TITLE
PHP Version 8.1

### ISSUE THREAD

**Issue by remicollet** [remicollet/remirepo#177]
Accodring to  [PHP roadmap](https://wiki.php.net/todo/php81) version 8.1.0 GA is planed for end of year

Plan is

* provides SCL only for alpha/beta
* provides both SCL and base packages for RC

Start to test, fix and build extensions, especially after RC1 (final API)

Current state

* php81-php-8.1.0~**alpha1**-1

Extensions (checked are available as RPM, not checked have been tested but not built, missing have not been tested yet) :

- [x] amqp 1.11.0beta
- [x] apcu 5.1.21
- [x] apfd 1.0.2 using patch from [PR #4](https://github.com/m6w6/ext-apfd/pull/4)
- [x] ast 1.0.12
- [x] base58 1.0.2
- [x] bitset 3.0.1
- [x] brotli 0.13.1
- [x] couchbase 3.2.0 was fixed by [PR #33](https://github.com/couchbase/php-couchbase/pull/33)
- [x] crypto 0.3.2
- [x] csv 0.4.1
- [x] datadog_trace 0.66.0, partially fixed by [PR #1274](https://github.com/DataDog/dd-trace-php/pull/1274)
- [x] dbase 7.1.0
- [x] decimal 1.4.0 (some tests need to be fixed)
- [x] dio 0.2.0
- [x] ds 1.3.0, using upstream patches and [PR #187](https://github.com/php-ds/ext-ds/pull/187)
- [x] eio 3.0.0RC2  (some tests need to be fixed)
- [x] **env** not compatible but seems **dead** ?
- [x] ev 1.1.3 with patch send upstream by email
- [x] event 3.0.5 (previous with patch, send upstream by email)
- [x] excimer 1.0.2  was fixed by [PR #2](https://github.com/wikimedia/php-excimer/pull/2)
- [x] fann 1.2.0RC1 using patches from [PR #2](https://github.com/bukka/phpc/pull/2) and [PR #43](https://github.com/bukka/php-fann/pull/43)
- [x] gearman 2.1.0 using upstream [patch](https://github.com/php/pecl-networking-gearman/commit/7da13e4babc17067b2b45d6b37041c3c8ed91637)
- [x] geoip 1.1.1  using upstream [patch](https://github.com/php/pecl-networking-geoip/commit/e24c5e54098958a1acc65b8830bc245c7d0662e6)
- [x] geos 1.0.0 with lot of patches since 7.0
- [x] geospatial 0.3.1
- [x] gmagick 2.0.6RC1 using patch from [PR #54](https://github.com/vitoc/gmagick/pull/54)
- [x] gnupg 1.5.0 using patch from [PR #35](https://github.com/php-gnupg/php-gnupg/pull/35)
- [ ] **handlebars** not ready
- [x] hdr_histogram 0.4.2 with previous patch for 8.0
- [x] http 4.1.0 using various upstream patches and [PR #118](https://github.com/m6w6/ext-http/pull/118)
- [x] http_message 0.2.2 with previous patch for 8.0
- [x] horde_lz4 1.0.10 with patches
- [ ] **ice** not ready
- [x] igbinary 3.2.3
- [x] imagick 3.5.1 was fixed by  [PR #413](https://github.com/Imagick/imagick/pull/413) and [PR #450](https://github.com/Imagick/imagick/pull/450)
- [x] inotify 3.0.0
- [x] ip2location 8.1.1
- [x] ip2proxy 3.0.1
- [x] json_post 1.0.2
- [x] jsonpath 0.9.3
- [x] krb5 1.1.4
- [x] leveldb 0.3.0
- [x] libvirt 0.5.5 with patches since 8.0
- [x] luasandbox 4.0.2
- [x] lz4 0.4.3
- [x] lzf 1.6.8
- [x] mailparse 3.1.1 using upstream [patch](https://github.com/php/pecl-mail-mailparse/commit/ae960dba8cb607296b7f85ca23f9d0a2462607d5)
- [x] maxminddb 1.10.1
- [x] mcrypt 1.0.4 using upstream [patch](https://github.com/php/pecl-encryption-mcrypt/commit/5b16bf1c97c1bbab400fc877285bf0919ae73256)
- [x] memcache 8.0 using patch from [PR #88](https://github.com/websupport-sk/pecl-memcache/pull/88)
- [x] memcached 3.1.5  using lot of patches and [PR #486](https://github.com/php-memcached-dev/php-memcached/pull/486)  + [PR #487](https://github.com/php-memcached-dev/php-memcached/pull/487)
- [x] memprof 3.0.1  using patch from [PR #54](https://github.com/arnaud-lb/php-memory-profiler/pull/54)
- [x] mongodb 1.11.0alpha1 was fixed upstream and by [PR #1240](https://github.com/mongodb/mongo-php-driver/pull/1240)
- [x] msgpack 2.1.2  using patch from [PR #156](https://github.com/msgpack/msgpack-php/pull/156) and [PR #157](https://github.com/msgpack/msgpack-php/pull/157)
- [x] mustache 0.9.2
- [x] mysql 1.0.0-dev
- [ ] **mysql_xdevapi** no ready
- [ ] **mysqlnd_azure** not ready
- [x] oauth 2.0.7
- [x] opencensus 0.3.0  (fix needed for test suite)
- [ ] **orng** not ready
- [x] pam 2.2.3
- [x] parle 0.8.2 using patch from [PR #28](https://github.com/weltling/parle/pull/28)
- [x] pcov 1.0.9
- [x] pcsc 0.5.1
- [ ] **pdlib** not yet ready
- [ ] **phalcon** not yet ready
- [x] phpiredis 1.0.2
- [x] pkcs11 1.0   using  patch from [PR #59](https://github.com/gamringer/php-pkcs11/pull/59) 
- [x] pq 2.1.8  using  patch from [PR #40](https://github.com/m6w6/ext-pq/pull/40) and [PR #41](https://github.com/m6w6/ext-pq/pull/41)
- [x] protobuf 3.18.0, was fixed by from [PR #8710](https://github.com/protocolbuffers/protobuf/pull/8710)
- [x] psr 1.1.0
- [x] raphf 2.0.1
- [x] rar 4.2.0 with upstream patches
- [x] realpath_turbo 2.0.0
- [x] redis 5.3.4
- [x] rdkafka 5.0.1 was fixed by  [PR #467](https://github.com/arnaud-lb/php-rdkafka/pull/467)
- [x] rpminfo 0.5.1
- [x] rrd 2.0.3
- [x] runkit7 4.0.0a3
- [x] seaslog 2.2.0
- [ ] **scoutapm** not ready
- [x] scrypt 1.4.2 with previous patches
- [x] sdl 2.5.0
- [x] selinux 0.5.0
- [x] simple_kafka_client 0.1.4 was fixed by [PR #54](https://github.com/php-kafka/php-simple-kafka-client/pull/54)
- [ ] **skywalking** not ready
- [x] smbclient 1.0.6
- [ ] **snuffleupagus** not ready
- [ ] **solr** no ready
- [x] ssdeep 1.1.0 with patch for 8+
- [x] ssh2 1.3.1
- [x] stats 2.0.3 with previous patches
- [x] stomp 2.0.2 using patch from [PR #14](https://github.com/php/pecl-tools-stomp/pull/14)
- [x] swoole 4.7.0 using patch from [PR #4335](https://github.com/swoole/swoole-src/pull/4335)
- [x] sync 1.1.2  (fix needed for test suite)
- [x] trader 0.5.1
- [x] translit 0.7.1
- [x] uploadprogress 1.1.4
- [x] uopz 7.0.0
- [x] uuid 1.2.0
- [x] varnish 1.2.6
- [x] vips 1.0.12
- [ ] **vld** not ready
- [x] wddx 1.0.0-dev
- [x] xattr 1.4.0
- [x] xdebug 3.1.0beta1
- [x] xdiff 2.1.0
- [x] xhprof 2.3.4, was fixed by [PR #61](https://github.com/longxinH/xhprof/pull/61)
- [x] xlswriter 1.4.0
- [x] xmldiff 1.1.3
- [x] xmlrpc 1.0.0RC2 with upstream [patch](https://github.com/php/pecl-networking-xmlrpc/commit/0f782ffe52cebd0a65356427b7ab72d48b72d20c)
- [x] xxtea 1.0.1 with previous patches
- [x] yac 2.3.0 using patch from [PR #120](https://github.com/laruence/yac/pull/120)
- [x] yaf 3.3.3  using patch from[PR #548](https://github.com/laruence/yaf/pull/548)
- [x] yaml 2.2.2 was fixed by [PR #60](https://github.com/php/pecl-file_formats-yaml/pull/60)
- [x] zip 1.19.3
- [x] zmq 1.1.3 using patches from [PR #216](https://github.com/zeromq/php-zmq/pull/216) and [PR #222](https://github.com/zeromq/php-zmq/pull/222)
- [x] zstd 0.10.0

Feedback welcome, feel free to ask for extensions you need for your tests.

**Comment by remicollet** [comment]
Updated:

*    php81-php-8.1.0~**alpha2**-1

**Comment by remicollet** [comment]
Updated:

*    php81-php-8.1.0~**alpha3**-1

**Comment by andypost** [comment]
uploadprogress needs some love

**Comment by remicollet** [comment]
@andypost AFAIK current version is a bit broken, but the main issue is that extension is only for mod_php. Nowadays nobody still use mod_php, but use FPM instead. And PHP have upload progress tracking available for years.... without this extension...

**Comment by remicollet** [comment]
@andypost _uploadprogress_ added to the repository

**Comment by remicollet** [comment]
Updated:

*    php81-php-8.1.0~**beta1**-1

**Comment by remicollet** [comment]
Updated:

*    php81-php-8.1.0~**beta2**-1

With new fixes / builds for

- http
- pq
- simple_kafka_client
- var_representation
- yac
- yaml

**Comment by andypost** [comment]
Xhprof also got update for 8.1beta

**Comment by andypost** [comment]
Links to yaf and yaml are broken

**Comment by remicollet** [comment]
@andypost copy/paste error fixed

**Comment by remicollet** [comment]
[8.1.0RC1 is released](https://www.php.net/archive/2021.php#2021-09-02-1)

New stack for PHP 8.1 as single / default version (php-* packages)

- php-**8.1.0~RC1**-1

Software Collections updated:

- php81-**php-8.1.0~rc1**-2

All extensions have been rebuild for new API version (20210902)

**Comment by remicollet** [comment]
Work of the day: fixed, built, and uploaded to the repository

- smbclient
- base58
- bitset
- brotli
- crypto
- decimal
- eio
- env
- gnupg (with [patch submitted upstream](https://github.com/php-gnupg/php-gnupg/pull/35))
- hdr_histrogram
- http_message
- ip2proxy
- leveldb
- luasandbox
- lz4
- mustache
- mysql
- orng
- parle  (with [patch submitted upstream](https://github.com/weltling/parle/pull/28))

**Comment by remicollet** [comment]
Work of the day: fixed, built, and uploaded to the repository

- pcsc
- pkcs11 with [patch submitted upstream](https://github.com/gamringer/php-pkcs11/pull/59)
- realpath_turbo 2.0.0
- rdkafka 5.0.0 with [patch submitted upstream](https://github.com/arnaud-lb/php-rdkafka/pull/467)
- seaslog
- scrypt
- stats
- sync
- trader
- translit
- varnish
- vips
- wddx
- xdiff
- xxtea

**Comment by remicollet** [comment]
[8.1.0RC2 is released](https://www.php.net/archive/2021.php#2021-09-16-1)

Updates:

- php-8.1.0~RC2-1
- php81-php-8.1.0~rc2-1

**Comment by DavidAnderson684** [comment]
Apologies if this is addressed somewhere else (I searched). On two separate CentOS 7 machines, PHP 8.1.0RC3 from this repo, running the /usr/bin/php81 binary gives me this output:

```
PHP Warning:  PHP Startup: Unable to load dynamic library 'intl' (tried: /opt/remi/php81/root/usr/lib64/php/modules/intl (/opt/remi/php81/root/usr/lib64/php/modules/intl: cannot open shared object file: No such file or directory), /opt/remi/php81/root/usr/lib64/php/modules/intl.so (/opt/remi/php81/root/usr/lib64/php/modules/intl.so: undefined symbol: __cxa_throw_bad_array_new_length)) in Unknown on line 0
PHP 8.1.0RC3 (cli) (built: Sep 28 2021 21:40:07) (NTS gcc x86_64)
Copyright (c) The PHP Group
Zend Engine v4.1.0RC3, Copyright (c) Zend Technologies
    with Xdebug v3.1.0beta2, Copyright (c) 2002-2021, by Derick Rethans
```

(I got the same on RC2 as well).

**Comment by remicollet** [comment]
Can reproduce (specific to EL-7.... please use a modern distro for modern versions).
Need to understand what happen again....

**Comment by remicollet** [comment]
@DavidAnderson684 fixed in new build (switching back from GCC 10 to GCC 8)

```
# php -v
PHP 8.1.0RC3 (cli) (built: Sep 28 2021 21:40:07) (NTS gcc x86_64)
Copyright (c) The PHP Group
Zend Engine v4.1.0RC3, Copyright (c) Zend Technologies

# php --ri intl

intl

Internationalization support => enabled
ICU version => 69.1
ICU Data version => 69.1
ICU Unicode version => 13.0

Directive => Local Value => Master Value
intl.default_locale => no value => no value
intl.error_level => 0 => 0
intl.use_exceptions => Off => Off

```

**Comment by remicollet** [comment]
[8.1.0RC3 is released](https://www.php.net/archive/2021.php#2021-09-30-1)

Updates:

- php-8.1.0~RC3-1
- php81-php-8.1.0~rc3-1

**Comment by remicollet** [comment]
@DavidAnderson684 switch back to GCC 10 for stack consistency, using libicu69 everything seems OK (8.1.0~RC3-3 builds)

Please check / confirm

**Comment by DavidAnderson684** [comment]
Yes, that fixes it for me, thank you.

**Comment by legoktm** [comment]
@remicollet do you have a build/test failure log for excimer? I just released 1.0.1 on PECL which contains [the patch](https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/php/excimer/+/426c788d58d96616b79c41def087796b0706d680) you had submitted earlier this year in case that was the issue.

**Comment by remicollet** [comment]
@legoktm previous patch was for PHP 8.0, see https://github.com/wikimedia/php-excimer/pull/2 for PHP 8.1

**Comment by remicollet** [comment]
Work of the day: fixed, built, and uploaded to the repository

- **ds** with [patch submitted upstream](https://github.com/php-ds/ext-ds/pull/187)
- **zmq** with [patch submitted upstream](https://github.com/zeromq/php-zmq/pull/222)

**Comment by remicollet** [comment]
[8.1.0 GA](http://php.net/releases/8_1_0.php) is released

Also announced on the [blog](https://blog.remirepo.net/post/2021/11/25/PHP-version-8.1.0-is-released) and [twitter](https://twitter.com/RemiRepository/status/1463941750150639621)
