### ISSUE TITLE
Fedora 35 - WIP tracker

### ISSUE THREAD

**Issue by remicollet** [remicollet/remirepo#184]
* Beta planed for Sept 14th or 21th
* Final planned for Oct 19th or 26th

Work list 

- [x] Repostiory setup
- [x] PHP 8.0 as base packages / module stream
- [x] PHP 8.1 as base packages / module stream
- [x] PHP 5.6 as SCL (219 packages)
- [x] PHP 7.0 as SCL (208 packages)
- [x] PHP 7.1 as SCL (213 packages)
- [x] PHP 7.2 as SCL (223 packages)
- [x] PHP 7.3 as SCL (222 packages)
- [x] PHP 7.4 as SCL (225 packages)
- [x] PHP 8.0 as SCL (190 packages)
- [x] PHP 8.1 as SCL (134 packages)

Broken packages under investigation

- [ ] php-pdlib
- [x] php-pecl-ds
- [x] php-pecl-mysql-xdevapi
- [x] php-pecl-vips reported as [#43](https://github.com/libvips/php-vips-ext/issues/43)

**Comment by remicollet** [comment]
Closing as Fedora 35 is now released and the repository fully populated.
