### ISSUE TITLE
PHP version 8.2

### ISSUE THREAD

**Issue by remicollet** [remicollet/remirepo#206]
According to  [PHP roadmap](https://wiki.php.net/todo/php82) version 8.2.0 GA is planed for end of year

Plan is

* provides SCL only for alpha/beta
* provides both SCL and base packages (modules) for RC

Start to test, fix and build extensions, especially after RC1 (final API)

Current state

* php82-php-8.2.0~**rc6**-19  (Software Collections)
* php-8.2.0~**RC6**-7 (Module))

Extensions (checked are available as RPM, not checked have been tested but not built, missing have not been tested yet) :

- [x] ahorasick 0.0.7 with patches
- [x] amqp 1.11.0 using [PR #118](https://github.com/php-amqp/php-amqp/pull/418)
- [x] apcu 5.1.22
- [x] apfd 1.0.3
- [x] ast 1.1.0
- [x] awscrt 1.0.9
- [x] base58 1.0.2
- [x] bitset 3.0.1 with patch from [pr #14](https://github.com/php/pecl-numbers-bitset/pull/14)
- [x] brotli 0.13.1
- [x] cassandra (nano-interactive fork) 1.3.7 with patch from [pr #36](https://github.com/nano-interactive/ext-cassandra/pull/36)
- [x] couchbase 4.0.0
- [x] crypto 0.3.2
- [x] csv 0.4.2
- [ ] datadog_trace [not yet compatible](https://github.com/DataDog/dd-trace-php/issues/1738)
- [x] dbase 7.1.1 with upstream patches for test suite
- [x] decimal 1.4.0 with patches
- [x] dio 0.2.1
- [x] ds 1.4.0
- [x] eio 3.0.0RC4
- [x] env 0.2.1 with patches
- [x] ev 1.1.6RC1
- [x] event 3.0.8
- [x] excimer 1.0.4
- [x] fann 1.2.0RC1
- [x] gearman 2.1.0
- [x] geoip 1.1.1 with patches
- [x] geos 1.1.0 with patch from [#27](https://git.osgeo.org/gitea/geos/php-geos/issues/27)
- [x] geospatial 0.3.2
- [x] gmagick 2.0.6 with patches
- [x] gnupg 1.5.1
- [x] grpc 1.48.1
- [x] hdr_histogram 0.4.2
- [x] http 4.2.3
- [ ] http_message is not yet compatible
- [ ] ice is not yet compatible (**zephir** issue)
- [x] igbinary 3.2.7
- [x] imagick 3.7.0
- [x] inotify 3.0.0
- [x] ion 0.2.1 fixed upstream
- [x] ip2location 8.1.2
- [x] ip2proxy 3.0.3
- [x] jsonpath 1.0.0
- [x] json-post 1.1.0
- [x] krb5 1.1.4
- [x] leveldb 0.3.0
- [x] libvirt 0.5.6
- [x] luasandbox 4.1.0
- [x] lz4 0.4.3
- [x] lzf 1.7.0
- [x] mailparse 3.1.4 was fixed upstream [patch](https://github.com/php/pecl-mail-mailparse/commit/e633e2308afe992a2eaf2bbf3f0ab34fc420ce77)
- [x] maxmindb 1.11.0
- [x] mcrypt 1.0.5
- [x] memcache 8.0
- [x] memcached 3.2.0 with upstream [patch](https://github.com/php-memcached-dev/php-memcached/commit/fc388e65e7ceab9e6d52bc77b6306f71db981873)
- [x] memprof 3.0.2
- [x] mongodb 1.14.0
- [x] msgpack 2.2.0RC2
- [x] mustache using patch from [pr #67](https://github.com/jbboehr/php-mustache/pull/67)
- [x] mysql 1.0.0DEV
- [x] mysql_xdevapi 8.0.30
- [x] nsq 3.5.1
- [x] oauth 2.0.7 with patch from [pr #24](https://github.com/php/pecl-web_services-oauth/pull/24)
- [x] opencensus 0.3.0 with patch from [pr #286](https://github.com/census-instrumentation/opencensus-php/pull/286)
- [x] openswoole 4.12.0
- [x] pam 2.2.4
- [x] parle 0.8.3
- [x] pcsc 0.5.1
- [x] pcov 1.0.11
- [ ] phalcon is not yet compatible (**zephir** issue)
- [x] phpiredis 1.0.1
- [x] pkcs 1.1.1 with patch from [pr #70](https://github.com/gamringer/php-pkcs11/pull/70)
- [x] pq 2.2.0 with upstream fix
- [x] protobuf 3.21.5
- [x] ps 1.4.4
- [x] psr 1.2.0
- [x] quickhash 1.1.1
- [x] raphf 2.0.1
- [x] rar 4.2.0 using patch from [pr #18](https://github.com/cataphract/php-rar/pull/18)
- [x] rdkafka 6.0.3
- [x] realpath_turbo 2.0.0 with patch from [pr #20](https://github.com/Whissi/realpath_turbo/pull/20)
- [x] recode 1.0.0DEV
- [x] redis 5.3.7
- [x] rpminfo 0.6.0
- [x] rrd 1.2.0
- [x] runkit 4.0.0e6
- [x] scoutapm 1.8.2 using patch from [pr #124](https://github.com/scoutapp/scout-apm-php-ext/pull/124)
- [x] scrypt 1.4.3
- [x] sdl 2.7.0
- [x] sdl_image 0.4.0
- [x] sdl_mixer 0.4.0
- [x] sdl_ttf 0.3.0
- [x] seaslog 2.2.0
- [x] seassnowflake 1.0.0 with patch from [pr #9](https://github.com/SeasX/SeasSnowflake/pull/9)
- [x] selinux 0.6.0
- [x] simdjson 2.0.3
- [x] simple_kafka_client 0.1.4
- [x] skywalking 5.0.1
- [x] smbclient 1.0.6
- [x] snappy 0.2.1
- [ ] snuffleupagus is not yet compatible
- [x] solr 2.6.0, was fixed by [pr #39](https://github.com/php/pecl-search_engine-solr/pull/39)
- [x] sqlsrv 5.10.1
- [x] ssdeep 1.1.0-11
- [x] ssh2 1.3.1
- [x] stats 2.0.3
- [x] stomp 2.0.3
- [x] swoole 4.8.12 / 5.0.1
- [x] sync 1.1.2 with 2 failed tests (deprecation)
- [x] teds 1.2.4
- [ ] tensor is not yet compatible (**zephir** issue)
- [x] trader 0.5.1
- [x] translit 0.7.1
- [x] trie 0.1.2
- [x] uopz 7.1.1 but 1 failed test
- [x] uploadprogress 2.0.2
- [x] uuid 1.2.0
- [x] var_representation 0.1.2
- [x] varnish 1.2.6
- [x] vips 1.0.13
- [x] vld 0.18.0
- [x] xattr 1.4.0
- [x] xdebug 3.2.0alpha1
- [x] xdiff 2.1.1
- [x] xhprof 2.3.6
- [x] xlswriter 1.5.2 with patch from [pe #451](https://github.com/viest/php-ext-xlswriter/pull/451)
- [x] xmldiff 1.1.3
- [x] xmlrpc 1.0.0RC3 with [upstream patch](https://github.com/php/pecl-networking-xmlrpc/commit/e83ef297bb23cc4e4de2cfb4bc83433902a196ef) for test suite
- [x] xxtea 1.0.11 with patches
- [x] xz 1.1.2
- [x] yac 2.3.1
- [x] yaconf 1.1.2
- [x] yaf 3.3.5 with patch from [pr #579](https://github.com/laruence/yaf/pull/579)
- [x] yar 2.3.2 with patch from [pr #177](https://github.com/laruence/yar/pull/177) after [PHP pr #9576](https://github.com/php/php-src/pull/9576) merged
- [x] yaml 2.2.2
- [x] yaz 1.2.4
- [x] zephir_parser 1.5.1
- [x] zip 1.21.1
- [x] zmq 1.1.3 using [PR #228](https://github.com/zeromq/php-zmq/pull/228)
- [x] zstd 0.11.0

Feedback welcome, feel free to ask for extensions you need for your tests.

**Comment by remicollet** [comment]
Now also available as module in the php:remi-8.2 stream

**Comment by mnapoli** [comment]
Sorry if this is a dumb question, but is sodium missing from the `php82` package?

Here is what I do:

```
yum install -y \
        https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm \
        https://rpms.remirepo.net/enterprise/remi-release-7.rpm \
        yum-utils \
        epel-release \
        curl

yum-config-manager --enable remi-php82

yum update -y && yum upgrade -y

yum install --setopt=skip_missing_names_on_install=False -y \
        php82-php-cli-8.2.0~rc5-18.el7.remi.x86_64
```

(I want to install an exact version)

`php -i` shows that sodium is not installed.

Thank you for the help!

**Comment by mnapoli** [comment]
Oh additionally, as a side question relating to the PHP 8.2 package:

https://rpms.remirepo.net/enterprise/7/php82/x86_64/repoview/php-cli.html shows that the version is `php-8.2.0~RC5-6.el7.remi.x86_64`. However `yum install php82-php-cli-8.2.0~RC5-6.el7.remi.x86_64` fails as there is no such package.

I had to find out that the version is actually `php82-php-cli-8.2.0~rc5-18.el7.remi.x86_64`. Should I look somewhere else (different web page) to find the latest version available?

**Comment by remicollet** [comment]
@mnapoli confused by module (single version) and SCL (multiple versions), see [FAQ](https://blog.remirepo.net/pages/English-FAQ#scl) and 

* https://rpms.remirepo.net/enterprise/7/php82/x86_64/repoview/php-cli.html  (module)
* https://rpms.remirepo.net/enterprise/7/remi/x86_64/repoview/php82-php-cli.html (SCL)

Reminder: see the [Wizard](https://rpms.remirepo.net/wizard/) instructions for proper configuration / usage

**Comment by remicollet** [comment]
> php -i shows that sodium is not installed.

As for every extension, if you need it, you must install it (as explained by the wizard), so php-sodium or php82-php-sodium

What is wrong in your docker is that you enable "remi-php82" which provides the single version "php-*" and then install php82-php-cli, which is in "remi", or "remi-safe" repository (again, see the wizard)

You are also using the very old C7 distribution, which is close to its end of life, you should prefer a modern version (EL-8 or EL-9) especially to run modern software (as PHP 8.2). Everything is old on EL-7

**Comment by deleugpn** [comment]
We need EL-7 because of Amazon Linux 2, which is the OS behind AWS Lambda. Not sure if we can get EL-8 or EL-9 to work with AL2. If you have any pointers we would love it!

**Comment by mnapoli** [comment]
Thank you Remi for all the pointers and taking the time (even though I missed it in your FAQ), that was extremely useful!

Now everything is building fine, I'm switching all the builds to the module distribution: https://github.com/brefphp/aws-lambda-layers/pull/26

As Marco mentioned above, we are unfortunately stuck with Amazon Linux 2 for now :/  So far our attempts to use the EL-8 or EL-9 packages fail, but I guess that's not a surprise: https://github.com/brefphp/aws-lambda-layers/issues/22

**Comment by remicollet** [comment]
8.2 is released and announced
https://blog.remirepo.net/post/2022/12/08/PHP-version-8.2.0-is-released

**Comment by paulocesarborges** [comment]
Hello guys! Sorry for the confusion!
I need the .dll ZMQ for php 8.2 NTS, theres any place that i can find it?
Thank you a lot!!

**Comment by remicollet** [comment]
@paulocesarborges this out of topic here (this is for RPM users)
