### ISSUE TITLE
PHP Version 8.4

### ISSUE THREAD

**Issue by remicollet** [remicollet/remirepo#258]
According to  [PHP roadmap](https://wiki.php.net/todo/php84) version 8.4.0 GA is planed for end of year

Plan is

- [x] provides SCL only for alpha/beta
- [x] provides both SCL and base packages (modules) for RC

Start to test, fix and build extensions, especially after RC1 (final API)

**Current state**

* php-8.4.1-1  (Module stream as php:remi-8.4)
* php84-php-8.4.1-1  (Software Collections as php84)

**Extensions** (checked are available as RPM, not checked have been tested but not built, missing have not been tested yet) :

- [x] ahocorasick 0.0.7 with previous patches
- [x] amqp 2.1.2
- [x] apcu 5.1.23 ignoring 1 failed test
- [x] apfd 1.0.3
- [x] ast 1.1.2
- [x] awscrt 1.2.6
- [x] base58 1.0.2
- [x] bitset 3.2.0
- [x] brotli 0.15.0
- [x] bsdiff 0.1.2
- [x] cassandra 1.3.2 with previous patches
- [x] couchbase 4.2.2
- [x] crypto 0.3.2 using patch from [PR #42](https://github.com/bukka/php-crypto)
- [x] csv 0.4.2
- [x] dbase 7.1.1  with previous patches
- [x] decimal 1.5.0
- [x] dio 0.3.0
- [x] ds 1.5.0
- [x] eio 3.1.3
- [x] env 0.2.1  with previous patches
- [x] ev 1.2.0
- [x] event 3.1.4 was fixed using [patch](https://github.com/remicollet/event/commit/b70cd8c7ecdec41092c504ad3dba820d389c2928) for test suite failure
- [x] excimer 1.2.2 was fixed by  [PR #8](https://github.com/wikimedia/mediawiki-php-excimer/pull/8) for build failure
- [x] fann 1.2.0
- [x] gearman 2.1.2
- [x] geoip 1.1.1 with previous patches
- [x] geos 1.0.0 with previous patches
- [x] geospatial 0.3.2 using [PR #31](https://github.com/php-geospatial/geospatial/pull/31) for test suite
- [x] gmagick 2.0.6RC1
- [x] GnuPG 1.5.14
- [x] grpc 1.65.0
- [x] handlebars 1.0.0 using patch from [PR #78](https://github.com/jbboehr/php-handlebars/pull/78) for test suite failure
- [x] hdr_histogram 0.5.0
- [x] http using [PR #135](https://github.com/m6w6/ext-http/pull/135) for build failure
- [x] igbinary 3.2.16, using  [PR #393](https://github.com/igbinary/igbinary/pull/393), was fixed by [PR #390](https://github.com/igbinary/igbinary/pull/390) for test suite failure
- [x] imagick 3.7.0
- [x] imap 1.0.2 with upstream patches
- [ ] immutable_cache build **failure**
- [x] ion 0.2.1 using [PR #10](https://github.com/awesomized/ext-ion/pull/10) for test suite failure
- [x] inotify 3.0.0
- [x] ip2location 8.2.0
- [x] ip2proxy 3.0.3
- [x] jsonpath 2.1.0
- [x] json_post 1.1.0
- [x] krb5 1.2.2
- [x] leveldb 0.3.0
- [x] libvirt 0.5.8
- [x] LuaSanbox 4.1.2
- [x] lz4 0.4.3
- [x] lzf 1.7.0
- [x] mailparse 3.1.8, was fixed by [patch](https://github.com/php/pecl-mail-mailparse/commit/56c80d21dc57cae955c496d7b4bc1f3c388788df) 
- [x] maxminddb 1.11.1
- [x] mcrypt 1.0.7 using [PR #19](https://github.com/php/pecl-encryption-mcrypt/pull/19) for build failure
- [x] memcache 8.2
- [x] memcached 3.2.0
- [x] memprof 3.0.2
- [x] mongodb 1.19..3
- [x] msgpack 3.0.0RC1, previously using [PR #174](https://github.com/msgpack/msgpack-php/pull/174) for test suite failure
- [x] mustache 0.9.3
- [x] mysql 1.0.0-dev
- [ ] mysql-xdevapi build **failure**
- [x] mysqlnd-krb5 1.0.0
- [x] nsq 3.5.1
- [x] oauth 2.0.9 was fixed by [PR #30 ](https://github.com/php/pecl-web_services-oauth/pull/30)for new build failure
- [x] oci8 3.4.0
- [ ] opencensus build **failure**, project has been **archived**
- [ ] openswoole build **failure**
- [x] opentelemetry 1.1.0beta3
- [x] PAM 2.2.5
- [x] parle 0.8.5
- [x] pcsc 0.5.1
- [x] pcov using [PR #111](https://github.com/krakjoe/pcov/pull/111) for build failure
- [ ] pdlib build **failure**
- [x] pdo_oci 1.1.0
- [x] phpiredis 1.0.1
- [x] php_trie 0.1.2
- [x] phpy 1.0.6
- [x] pkcs11 1.1.2
- [x] pq 2.2.3
- [x] protobuf 4.27.2
- [x] ps 1.4.4
- [x] pspell 1.0.1
- [ ] psr test suite **failure**
- [x] quickhash 1.1.1
- [x] raphf 2.0.1
- [x] rdkafka 6.0.3
- [x] realcache_turbo 3.0.4 with previous patches
- [x] recode 1.0.0-dev
- [x] redis 6.0.2 with upstream patches
- [ ] rnp test suite **failure** (segfault)
- [x] rpminfo 1.1.0
- [x] rrd 2.0.3
- [ ] scoutapm test suite **failure**
- [x] scrypt 2.0.1
- [x] sdl 2.7.0
- [x] sdl_image 0.4.0
- [x] sdl_mixer 0.4.0
- [x] sdl_ttf 0.3.0
- [x] SeasClick 0.1.1
- [ ] SeasLog build **failure**
- [x] SeasSnowflake 1.0.0  with previous patches
- [x] selinux 0.6.0
- [x] simple_kafka_client 0.1.4
- [x] skywalking 5.0.1
- [ ] skywalking_agent build **failure**
- [x] smbclient 1.1.1
- [x] snappy 0.2.1
- [x] snuffleupagus 0.11.0
- [ ] solr build **failure**
- [x] ssdeep 1.1.0 with previous patches
- [x] ssh2 1.4.1
- [x] stats 2.0.3 with previous patches
- [x] stomp 2.0.3
- [x] swoole 6.0.0-beta using [PR #5537](https://github.com/swoole/swoole-src/pull/5537)
- [x] sync 1.1.3
- [x] teds 1.3.0 using [PR #205](https://github.com/TysonAndre/pecl-teds/pull/205)
- [x] trader 0.5.1
- [x] transit 0.7.1
- [ ] uopz test suite **failure**
- [x] uploadprogress 2.0.2
- [x] uuid 1.2.0
- [x] uv 0.3.0
- [x] var_representation 0.1.4
- [x] varnish 1.2.6
- [x] vips 1.0.13
- [x] vld 0.18.0 using upstream patches and [PR #83](https://github.com/derickr/vld/pull/83)
- [x] xattr 1.4.0
- [x] xdebug 3.4.0beta1
- [x] xdiff 2.1.1
- [x] xhprof 2.3.10, was fixed by [PR #87](https://github.com/longxinH/xhprof/pull/87)
- [x] xlswriter 1.5.7 using [PR #531](https://github.com/viest/php-ext-xlswriter/pull/531)
- [x] xmldiff 1.1.3 using [PR #2](https://github.com/php/pecl-xml-xmldiff/pull/2)
- [x] xpass 1.0.0RC1
- [x] xxtea 1.0.11  with previous patches
- [x] yac 2.3.1
- [x] yaconf 1.1.2
- [x] yaf 3.3.6 using [PR #594](https://github.com/laruence/yaf/pull/594)
- [x] yaml 2.2.4
- [x] yar 2.3.3
- [x] yaz 1.2.4
- [x] zephir_parser 1.6.1
- [x] zip 1.22.3 with upstream patches
- [x] zmq 1.1.3 with previous patches
- [x] zstd 0.13.3

**Additional SAPIs:**

- [x] unit-php 1.32.1
- [x] uwsgi-php 2.0.26

Feedback is welcome, feel free to ask for extensions you need for your tests.

**Comment by remicollet** [comment]
New build (RC1) are now available both as SCLs and modules

**Comment by remicollet** [comment]
All compatible extensions are now available (so this issue is considered as "fixed")

Broken build will need more work

**Comment by remicollet** [comment]
**PHP 8.4.1** is announced upstream: https://www.php.net/archive/2024.php#2024-11-21-4
And on the blog: https://blog.remirepo.net/post/2024/11/21/PHP-version-8.4-is-released

**Comment by akebar** [comment]
There is no pecl-parallel extension for 8.4 and no zts-php build?

**Comment by remicollet** [comment]
> There is no pecl-parallel extension for 8.4 and no zts-php build?

Indeed

Too much issues and segfault with ZTS

**Comment by akebar** [comment]
> > There is no pecl-parallel extension for 8.4 and no zts-php build?
> 
> Indeed
> 
> Too much issues and segfault with ZTS
> 
> ZTS build dropped with PHP 8.4, and for all versions in Fedora >= 41 and EL >= 10 packages

OK. So what's the future for the parallel extension?

**Comment by andypost** [comment]
FYI fixed last issue on arm64 https://github.com/php/php-src/issues/16902#issuecomment-2496160445

**Comment by remicollet** [comment]
> OK. So what's the future for the parallel extension?

I will provide new builds only for old versions

I'm sorry, but maintaining 11 PHP versions, 2 architectures, and 6 distributions is a lot of work, and ZTS doubles the work for very, very little benefit.
