### ISSUE TITLE
Enterprise Linux 10 repository

### ISSUE THREAD

**Issue by remicollet** [remicollet/remirepo#276]
- [x] RHEL-10-beta is released
- [x] EPEL-10 is open
- [x] Repository layout
- [x] 2024 GPG Key
- [x] PR to distribution-gpg-keys
- [x] FAQ + Config pages
- [x] remi-release
- [x] php:remi-7.4 stream
- [x] php:remi-8.0 stream
- [x] php:remi-8.1 stream
- [x] php:remi-8.2 stream
- [x] php:remi-8.3 stream
- [x] php:remi-8.4 stream
- [x] php74 SCL
- [x] php80 SCL
- [x] php81 SCL
- [x] php82 SCL
- [x] php83 SCL
- [x] php84 SCL
- [x] 100% php extensions (all PHP versions)
    - [x] 25%
    - [x] 50%
    - [x] 75%
- [x] Wizard
- [x] other packages (Memcached...)
- [ ] Final change for GA (wizard, F39 EOL, index)

Notice: I choose to stop providing **ZTS** builds of PHP

**Comment by remicollet** [comment]
Most extensions are now available

Missing have been forgotten (please report) or have missing dependencies

- [ ] php-**pdlib** #2326940 dlib
- [ ] php-pecl-**cmark** #2328886 cmark
- [ ] php-pecl-**fann** #2326997 fann
- [ ] php-pecl-**geoip** GeoIP
- [ ] php-pecl-**gmagick** #2328887 GraphicsMagic
- [ ] php-pecl-**vips** #2327000 vips => matio
- [ ] php-pecl-**interbase** #2319128 firebird
- [ ] php-pecl-**leveldb** #2327826 leveldb
- [ ] php-pecl-**ps** #2328667 pslib
- [ ] php-pecl-**sdl-mixer** #2314001 SDL2_mixer
- [ ] php-pecl-**sdl-ttf** #2313994 SDL2_ttf
- [ ] php-pecl-**xmldiff** diffmark
- [ ] php-pecl-**yaz** libyaz

**Comment by pdvSNnz** [comment]
Any plans to provide an additional x84_64_v2 build as AlmaLinux does for itself and EPEL?

**Comment by remicollet** [comment]
> Any plans to provide an additional x84_64_v2 build as AlmaLinux does for itself and EPEL?

Sorry, no, builders are using official RHEL repositories.

So I follow RH idea
- old hardware => stay on EL-9 (and update hardware before 2032)
- new hardware => use EL-10

And EPEL required by lot of packages also don't have x86_64 v2

So too much work for an additional arch.

**Comment by pdvSNnz** [comment]
Alma also provides an 1:1 rebuild repo of EPEL for x86_64_v2 on top. Maybe this could be an easy starting point for another buildtree with arch x86_64_v2.
